name: Build Check

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build project
        run: |
          mvn clean install

      - name: Run unit tests
        run: |
          mvn test

      - name: Check test results
        run: |
          mvn surefire-report:report-only
          cat target/site/surefire-report.html

#        env:
#          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}